remote_theme : mmistakes/minimal-mistakes
# General Jekyll Config
highlighter: rouge
url: "https://Foxlee1015.github.io"
baseurl: ""
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
category_dir: category/
